"""Stub file for custom_components/reflex_schedule_x/schedule_x.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, Optional
from reflex_components_core.core.breakpoints import Breakpoints
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from typing import TypedDict
import reflex as rx
from reflex_base.components.component import MemoizationLeaf, NoSSRComponent
from reflex_base.utils.imports import ImportDict

SCHEDULE_X_VERSION = "4.8.0"
"Version of the @schedule-x/* npm packages bundled by this component."
TEMPORAL_POLYFILL_VERSION = "0.3.0"
"temporal-polyfill version required by @schedule-x/calendar as peer dependency."
_SX_PACKAGES = (
    "calendar",
    "calendar-controls",
    "current-time",
    "date-picker",
    "event-modal",
    "event-recurrence",
    "events-service",
    "ical",
    "scroll-controller",
    "theme-default",
    "theme-shadcn",
    "time-picker",
    "timezone-select",
    "translations",
)
LIB_DEPENDENCIES: list[str]
_JSX_MODULE = rx.asset("schedule_x.jsx", shared=True)
_LIBRARY = _JSX_MODULE.importable_path
THEME_CSS = {"default": "@schedule-x/theme-default/dist/index.css", "shadcn": "@schedule-x/theme-shadcn/dist/index.css"}
ViewName = Literal["day", "week", "month-grid", "month-agenda", "week-agenda", "list"]
ThemeName = Literal["default", "shadcn"]
DatetimeFormat = Literal["naive", "iso"]
VIEWS: tuple[str, ...]
SLOT_NAMES: tuple[str, ...]
"Custom component slots supported by Schedule-X (see schedule-x.dev/docs/frameworks/react)."

class CalendarEvent(TypedDict, total=False):
    id: str | int
    title: str
    start: str
    end: str
    description: str
    location: str
    people: list[str]
    calendarId: str
    rrule: str
    exdate: list[str]
    is_all_day: bool

class DateRange(TypedDict):
    start: str
    end: str

class RenderInfo(TypedDict):
    view: str
    date: str
    range: DateRange | None

class SlotAction(TypedDict):
    action: str
    slot: str
    event: CalendarEvent | None
    date: str | None

class ScheduleX(NoSSRComponent, MemoizationLeaf):
    def add_imports(self) -> ImportDict: ...
    def add_style(self) -> dict[str, Any] | None: ...
    @classmethod
    def create(
        cls,
        *children,
        events: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        background_events: Var[list[dict[str, Any]]] | list[dict[str, Any]] | None = None,
        calendars: Var[dict[str, dict[str, Any]]] | dict[str, dict[str, Any]] | None = None,
        views: Var[list[str]] | list[str] | None = None,
        default_view: Var[str] | str | None = None,
        view: Var[str] | str | None = None,
        selected_date: Var[str] | str | None = None,
        min_date: Var[str] | str | None = None,
        max_date: Var[str] | str | None = None,
        locale: Var[str] | str | None = None,
        timezone: Var[str] | str | None = None,
        first_day_of_week: Var[int] | int | None = None,
        translations: Var[dict[str, dict[str, str]]] | dict[str, dict[str, str]] | None = None,
        day_boundaries: Var[dict[str, str]] | dict[str, str] | None = None,
        week_options: Var[dict[str, Any]] | dict[str, Any] | None = None,
        month_grid_options: Var[dict[str, Any]] | dict[str, Any] | None = None,
        month_agenda_options: Var[dict[str, Any]] | dict[str, Any] | None = None,
        show_week_numbers: Var[bool] | bool | None = None,
        is_responsive: Var[bool] | bool | None = None,
        small_breakpoint: Var[int] | int | None = None,
        skip_animations: Var[bool] | bool | None = None,
        skip_validation: Var[bool] | bool | None = None,
        date_picker: Var[dict[str, Any]] | dict[str, Any] | None = None,
        theme: Var[str] | str | None = None,
        is_dark: Var[bool] | bool | None = None,
        current_time_indicator: Var[bool] | bool | None = None,
        current_time_full_week_width: Var[bool] | bool | None = None,
        event_modal: Var[bool] | bool | None = None,
        initial_scroll: Var[str] | str | None = None,
        scroll_to: Var[str] | str | None = None,
        recurrence: Var[bool] | bool | None = None,
        ical_data: Var[str] | str | None = None,
        timezone_select: Var[bool] | bool | None = None,
        datetime_format: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_calendar_render: Optional[EventType[()] | EventType[RenderInfo]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_click_agenda_date: Optional[EventType[()] | EventType[str]] = None,
        on_click_date: Optional[EventType[()] | EventType[str]] = None,
        on_click_date_time: Optional[EventType[()] | EventType[str]] = None,
        on_click_plus_events: Optional[EventType[()] | EventType[str]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click_agenda_date: Optional[EventType[()] | EventType[str]] = None,
        on_double_click_date: Optional[EventType[()] | EventType[str]] = None,
        on_double_click_date_time: Optional[EventType[()] | EventType[str]] = None,
        on_double_click_event: Optional[EventType[()] | EventType[CalendarEvent]] = None,
        on_error: Optional[EventType[()] | EventType[str]] = None,
        on_event_click: Optional[EventType[()] | EventType[CalendarEvent]] = None,
        on_event_update: Optional[EventType[()] | EventType[CalendarEvent]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_range_update: Optional[EventType[()] | EventType[DateRange]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_day_into_view: Optional[EventType[()] | EventType[str]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_selected_date_update: Optional[EventType[()] | EventType[str]] = None,
        on_slot_action: Optional[EventType[()] | EventType[SlotAction]] = None,
        on_unmount: Optional[EventType[()]] = None,
        on_view_change: Optional[EventType[()] | EventType[str]] = None,
        **props,
    ) -> "ScheduleX":
        """Create the calendar.

        Args:
            *children: ``schedule_x_slot`` components (custom components).
            events: Calendar events. Each dict needs `id`, `start` and `end`; `start`/`end` accept 'YYYY-MM-DD' (all-day), 'YYYY-MM-DD HH:mm' (in `timezone`), ISO strings with offset, or RFC 9557 strings. Optional: title, description, location, people, calendarId (or calendar_id), rrule, exdate, _options, _customContent and any custom key.
            background_events: Background events: dicts with start, end, style (CSS dict) and optional title/rrule/exdate.
            calendars: Calendar categories keyed by id: {colorName, label, lightColors: {main, container, onContainer}, darkColors}.
            views: Views to enable: day, week, month-grid, month-agenda, week-agenda, list. Defaults to day/week/month-grid/month-agenda.
            default_view: View shown on first render.
            view: Controlled current view. Updates the running calendar when it changes.
            selected_date: Selected date 'YYYY-MM-DD'. Updates the running calendar when it changes.
            min_date: Minimum navigable date 'YYYY-MM-DD'.
            max_date: Maximum navigable date 'YYYY-MM-DD'.
            locale: Locale such as 'en-US' or 'es-ES'. Defaults to 'en-US'.
            timezone: IANA timezone, e.g. 'America/Caracas'. Defaults to 'UTC'.
            first_day_of_week: First day of the week: 1 = Monday ... 7 = Sunday.
            translations: Translation overrides merged over the built-in ones, keyed by locale: {'en-US': {'Week': '4 days'}}.
            day_boundaries: Visible hours in week/day grids: {'start': '06:00', 'end': '18:00'}.
            week_options: Week grid options: gridHeight, nDays, eventWidth, timeAxisFormatOptions, eventOverlap, gridStep (snake_case accepted).
            month_grid_options: Month grid options: {'nEventsPerDay': 4}.
            month_agenda_options: Month agenda options: {'nEventIndicatorsPerDay': 3}.
            show_week_numbers: Show week numbers.
            is_responsive: Switch to small-screen views below the breakpoint. Defaults to true.
            small_breakpoint: Custom width (px) below which the calendar counts as small.
            skip_animations: Disable navigation transitions.
            skip_validation: Skip event validation (faster for large data sets).
            date_picker: Options for the header date picker (e.g. {'placement': 'bottom-end'}).
            theme: 'default' or 'shadcn'. Use a literal value; one theme per app.
            is_dark: Dark mode. Can be bound to rx.color_mode == 'dark'.
            current_time_indicator: Enable the current-time plugin.
            current_time_full_week_width: Draw the current-time line across the whole week.
            event_modal: Enable the event-modal plugin (customizable with the 'eventModal' slot).
            initial_scroll: Enable the scroll-controller plugin with this initial time, e.g. '07:50'.
            scroll_to: Scroll the week/day grid to 'HH:mm' whenever this changes (needs initial_scroll).
            recurrence: Enable the event-recurrence plugin (RFC 5545 rrule / exdate on events).
            ical_data: iCalendar (.ics) text to load through the ical plugin.
            timezone_select: Show the timezone-select plugin in the header.
            datetime_format: Format of date-times sent to Python: 'naive' ('YYYY-MM-DD HH:mm' in the calendar timezone) or 'iso' (RFC 9557).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_event_click: An event was clicked.
            on_double_click_event: An event was double-clicked.
            on_event_update: An event was changed by an interactive plugin (drag & drop, resize, ...).
            on_range_update: The visible range changed.
            on_selected_date_update: The selected date changed.
            on_view_change: The active view changed.
            on_click_date: A month-grid date was clicked.
            on_double_click_date: A month-grid date was double-clicked.
            on_click_date_time: The week/day time grid was clicked.
            on_double_click_date_time: The week/day time grid was double-clicked.
            on_click_agenda_date: A month-agenda date was clicked.
            on_double_click_agenda_date: A month-agenda date was double-clicked.
            on_click_plus_events: The '+ N events' button was clicked.
            on_scroll_day_into_view: A day scrolled into view in the list view (use it to lazy-load events).
            on_calendar_render: The calendar finished rendering.
            on_slot_action: A schedule_x_action inside a slot was clicked.
            on_error: The calendar could not be created.
            **props: Calendar props.

        Returns:
            The component.
        """
        ...

class ScheduleXSlot(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        slot_name: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScheduleXSlot":
        """Create a slot.

        Args:
            *children: The content rendered inside the slot.
            slot_name: Slot to fill. One of: timeGridEvent, dateGridEvent, monthGridEvent, monthAgendaEvent, weekAgendaEvent, monthAgendaDateDots, eventModal, headerContentLeftPrepend, headerContentLeftAppend, headerContentRightPrepend, headerContentRightAppend, headerContent, weekGridDate, weekGridHour, monthGridDayName, monthGridDate.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: ``slot_name`` (or ``slot`` / first positional str).

        Returns:
            The component.

        Raises:
            ValueError: If the slot name is missing or unknown.
        """
        ...

class ScheduleXField(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        name: Var[str] | str | None = None,
        format: Var[str] | str | None = None,
        fallback: Var[str] | str | None = None,
        tag_name: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScheduleXField":
        """Create a field.

        Args:
            *children: A single string is used as the field name.
            name: Field name or dotted path in the slot props. Event fields: title, description, location, people, calendarId, start, end, id or custom keys. Virtual: time_range, date_range, calendar_label. Other slots: date, hour, day, jsDate.
            format: Optional format: time, date, datetime, weekday, weekday_short, day, month, hour, count, upper, json.
            fallback: Text shown when the field is empty.
            tag_name: HTML tag to render (default span).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: Component props.

        Returns:
            The component.
        """
        ...

class ScheduleXShow(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        name: Var[str] | str | None = None,
        negate: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScheduleXShow":
        """Create the conditional wrapper.

        Args:
            *children: Content. A leading string is used as the field name.
            name: Field to test, e.g. location, people, description or is_all_day.
            negate: Render when the field is falsy instead.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: Component props.

        Returns:
            The component.
        """
        ...

class ScheduleXEventCard(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        variant: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScheduleXEventCard":
        """Create the component.

        Args:
            *children: The children of the component.
            variant: 'container' (soft background, colored border) or 'main' (solid).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class ScheduleXAction(NoSSRComponent):
    @classmethod
    def create(
        cls,
        *children,
        action: Var[str] | str | None = None,
        close_modal: Var[bool] | bool | None = None,
        stop_propagation: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScheduleXAction":
        """Create the component.

        Args:
            *children: The children of the component.
            action: Action name delivered in the payload, e.g. 'delete'.
            close_modal: Close the event modal after the action.
            stop_propagation: Stop the click from reaching the calendar. Defaults to true.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class _ThemedPicker(NoSSRComponent):
    def add_imports(self) -> ImportDict: ...
    @classmethod
    def create(
        cls,
        *children,
        theme: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "_ThemedPicker":
        """Create the component.

        Args:
            *children: The children of the component.
            theme: 'default' or 'shadcn' stylesheet (literal).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class ScheduleXDatePicker(_ThemedPicker):
    @classmethod
    def create(
        cls,
        *children,
        value: Var[str] | str | None = None,
        locale: Var[str] | str | None = None,
        first_day_of_week: Var[int] | int | None = None,
        min: Var[str] | str | None = None,
        max: Var[str] | str | None = None,
        placement: Var[str] | str | None = None,
        dark: Var[bool] | bool | None = None,
        full_width: Var[bool] | bool | None = None,
        label: Var[str] | str | None = None,
        name: Var[str] | str | None = None,
        disabled: Var[bool] | bool | None = None,
        has_placeholder: Var[bool] | bool | None = None,
        timezone: Var[str] | str | None = None,
        theme: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[()] | EventType[str]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScheduleXDatePicker":
        """Create the component.

        Args:
            *children: The children of the component.
            value: Selected date 'YYYY-MM-DD'.
            locale: Locale, e.g. 'es-ES'.
            first_day_of_week: 1 = Monday ... 7 = Sunday.
            min: Minimum date 'YYYY-MM-DD'.
            max: Maximum date 'YYYY-MM-DD'.
            placement: Popup placement: top-start, top-end, bottom-start, bottom-end.
            dark: Dark mode.
            full_width: Stretch the input to its container.
            label: Input label.
            name: Input name.
            disabled: Disable the input.
            has_placeholder: Show a placeholder instead of a date when no value is set.
            timezone: IANA timezone used to compute 'today'.
            theme: 'default' or 'shadcn' stylesheet (literal).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: Selected date changed ('YYYY-MM-DD').
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

class ScheduleXTimePicker(_ThemedPicker):
    def add_imports(self) -> ImportDict: ...
    @classmethod
    def create(
        cls,
        *children,
        value: Var[str] | str | None = None,
        locale: Var[str] | str | None = None,
        dark: Var[bool] | bool | None = None,
        placement: Var[str] | str | None = None,
        label: Var[str] | str | None = None,
        name: Var[str] | str | None = None,
        is_12_hour: Var[bool] | bool | None = None,
        theme: Var[str] | str | None = None,
        style: Sequence[Mapping[str, Any]] | Mapping[str, Any] | Var[Mapping[str, Any]] | Breakpoints | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: Optional[EventType[()]] = None,
        on_change: Optional[EventType[()] | EventType[str]] = None,
        on_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_context_menu: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_double_click: Optional[EventType[()] | EventType[PointerEventInfo]] = None,
        on_focus: Optional[EventType[()]] = None,
        on_mount: Optional[EventType[()]] = None,
        on_mouse_down: Optional[EventType[()]] = None,
        on_mouse_enter: Optional[EventType[()]] = None,
        on_mouse_leave: Optional[EventType[()]] = None,
        on_mouse_move: Optional[EventType[()]] = None,
        on_mouse_out: Optional[EventType[()]] = None,
        on_mouse_over: Optional[EventType[()]] = None,
        on_mouse_up: Optional[EventType[()]] = None,
        on_scroll: Optional[EventType[()]] = None,
        on_scroll_end: Optional[EventType[()]] = None,
        on_unmount: Optional[EventType[()]] = None,
        **props,
    ) -> "ScheduleXTimePicker":
        """Create the component.

        Args:
            *children: The children of the component.
            value: Time 'HH:mm'.
            locale: Locale used for the buttons, e.g. 'es-ES'.
            dark: Dark mode.
            placement: Popup placement: top-start, top-end, bottom-start, bottom-end.
            label: Input label.
            name: Input name.
            is_12_hour: Use a 12-hour clock.
            theme: 'default' or 'shadcn' stylesheet (literal).
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_change: Time changed ('HH:mm').
            **props: The props of the component.

        Returns:
            The component.
        """
        ...

schedule_x = ScheduleX.create
schedule_x_slot = ScheduleXSlot.create
schedule_x_field = ScheduleXField.create
schedule_x_show = ScheduleXShow.create
schedule_x_event_card = ScheduleXEventCard.create
schedule_x_action = ScheduleXAction.create
schedule_x_date_picker = ScheduleXDatePicker.create
schedule_x_time_picker = ScheduleXTimePicker.create
